// words.js - 295語フル＋熟練度ランク(30倍版)

// ランク判定（30倍）
function getRank(count){
  if(count >= 3000) return "SS";
  if(count >= 1500) return "S";
  if(count >= 600) return "A";
  if(count >= 300) return "B";
  if(count >= 150) return "C";
  if(count >= 90) return "D";
  if(count >= 30) return "E";
  return "-";
}

// ★ 全295語をここに入れる（長いため分割して後で追記します）
const words = [
  { jp: "同じ", en: "same" },
  { jp: "経験する", en: "experience" },
  { jp: "実は", en: "actually" },
  { jp: "ラーメン", en: "ramen" },
  { jp: "瞬間", en: "instant" },
  { jp: "麺", en: "noodle" },
  { jp: "ところで", en: "by the way" },
  { jp: "金色の", en: "golden" },
  { jp: "シンガポール", en: "Singapore" },
  { jp: "飛行", en: "flight" },
  { jp: "到着する", en: "arrive" },
  { jp: "空港", en: "airport" },
  { jp: "すぐに", en: "soon" },
  { jp: "さようなら", en: "see you" },
  { jp: "～するつもり", en: "will" },
  { jp: "わくわくした", en: "excited" },
  { jp: "シーフード", en: "seafood" },
  { jp: "予約", en: "reservation" },
  { jp: "メーター", en: "meter" },
  { jp: "背が高い", en: "tall" },
  { jp: "重さがある", en: "weigh" },
  { jp: "トン", en: "ton" },
  { jp: "見つけた", en: "found" },
  { jp: "言葉", en: "language" },
  { jp: "例", en: "example" },
  { jp: "連絡する", en: "communicate" },
  { jp: "マレー語", en: "Malay" },
  { jp: "タミル語", en: "Tamil" },
  { jp: "例えば", en: "for example" },
  { jp: "絵を描くこと", en: "painting" },
  { jp: "壁", en: "wall" },
  { jp: "驚いた", en: "surprised" },
  { jp: "地域", en: "area" },
  { jp: "インド", en: "India" },
  { jp: "モスク", en: "mosque" },
  { jp: "文化", en: "culture" },
  { jp: "中国人街", en: "Chinatown" },
  { jp: "注文する", en: "order" },
  { jp: "トッピング", en: "topping" },
  { jp: "いろいろな", en: "various" },
  { jp: "風味", en: "flavor" },
  { jp: "しょうゆ", en: "soy sauce" },
  { jp: "塩", en: "salt" },
  { jp: "スピーチ", en: "speech" },
  { jp: "いつか", en: "sometime" },
  { jp: "もし〜なら", en: "if" },
  { jp: "加える", en: "add" },
  { jp: "バター", en: "butter" },
  { jp: "ぜひ〜したい", en: "would love to" },
  { jp: "興味がある", en: "be interested in" },
  { jp: "忘れる", en: "forget" },
  { jp: "種類", en: "kind" },
  { jp: "だから", en: "because" },
  { jp: "厚い", en: "thick" },
  { jp: "推薦する", en: "recommend" },
  { jp: "製造業者", en: "manufacturer" },
  { jp: "早く", en: "early" },
  { jp: "大体", en: "kind of" },
  { jp: "種類の", en: "kinds of" },
  { jp: "反映する", en: "reflect" },
  { jp: "気候", en: "climate" },
  { jp: "生きる", en: "lives" },
  { jp: "創造性", en: "creativity" },
  { jp: "シェフ", en: "chef" },
  { jp: "外国の", en: "foreign" },
  { jp: "変化", en: "variation" },
  { jp: "イタリア", en: "Italy" },
  { jp: "創造する", en: "create" },
  { jp: "ソース", en: "sauce" },
  { jp: "変える", en: "change" },
  { jp: "ナポリ", en: "Naples" },
  { jp: "出身である", en: "come from" },
  { jp: "ここは", en: "here is" },
  { jp: "設計する", en: "design" },
  { jp: "売上高", en: "turnover" },
  { jp: "住民", en: "resident" },
  { jp: "お願い", en: "favor" },
  { jp: "聞く", en: "ask" },
  { jp: "できた", en: "could" },
  { jp: "メニュー", en: "menu" },
  { jp: "職業", en: "career" },
  { jp: "情報", en: "information" },
  { jp: "国際的な", en: "international" },
  { jp: "託児所", en: "nursery" },
  { jp: "紙幣", en: "note" },
  { jp: "自分の", en: "own" },
  { jp: "鬼ごっこ", en: "tag" },
  { jp: "箸", en: "chopstick" },
  { jp: "絵本", en: "picture book" },
  { jp: "職業体験日", en: "career day" },
  { jp: "選んだ", en: "chose" },
  { jp: "選ぶ", en: "choose" },
  { jp: "色鮮やか", en: "colorful" },
  { jp: "図解", en: "illustration" },
  { jp: "かわいい", en: "pretty" },
  { jp: "教えた", en: "taught" },
  { jp: "教える", en: "teach" },
  { jp: "重要な", en: "important" },
  { jp: "月", en: "moon" },
  { jp: "横たえる", en: "lay" },
  { jp: "嘘", en: "lie" },
  { jp: "葉", en: "leaf" },
  { jp: "小さな", en: "tiny" },
  { jp: "毛虫", en: "caterpillar" },
  { jp: "梨", en: "pear" },
  { jp: "梅", en: "plum" },
  { jp: "思いつく", en: "come up" },
  { jp: "出てくる", en: "come out of" },
  { jp: "学ぶ", en: "learn" },
  { jp: "必要な", en: "necessary" },
  { jp: "調節する", en: "adjust" },
  { jp: "物語", en: "story" },
  { jp: "難しい", en: "difficult" },
  { jp: "文", en: "sentence" },
  { jp: "明確に", en: "clearly" },
  { jp: "理解する", en: "understand" },
  { jp: "ほほえむ", en: "smile" },
  { jp: "拍手する", en: "clap" },
  { jp: "嬉しい", en: "glad" },
  { jp: "大声の", en: "loud" },
  { jp: "真心こめて", en: "sincerely" },
  { jp: "何度も何度も", en: "again and again" },
  { jp: "これから先も", en: "from now on" },
  { jp: "小麦粉", en: "flour" },
  {jp: "キャベツ", en: "cabbage" },
  { jp: "カリカリ", en: "crispy" },
  { jp: "美味しい", en: "tasty" },
  { jp: "簡単に", en: "easily" },
  { jp: "材料", en: "ingredient" },
  { jp: "理由", en: "reason" },
  { jp: "調べる", en: "check" },
  { jp: "しかしながら", en: "however" },
  { jp: "簡単な", en: "easy" },
  { jp: "前に", en: "ago" },
  { jp: "古代の", en: "ancient" },
  { jp: "エジプト人", en: "Egyptian" },
  { jp: "置く", en: "put" },
  { jp: "棒", en: "stick" },
  { jp: "影", en: "shadow" },
  { jp: "伝えた", en: "told" },
  { jp: "話す", en: "tell" },
  { jp: "測る", en: "measure" },
  { jp: "なしで", en: "without" },
  { jp: "つぼ", en: "pot" },
  { jp: "穴", en: "hole" },
  { jp: "減る", en: "decrease" },
  { jp: "列", en: "line" },
  { jp: "火", en: "fire" },
  { jp: "燃やす", en: "burn" },
  { jp: "ろうそく", en: "candle" },
  { jp: "与えた", en: "gave" },
  { jp: "与える", en: "give" },
  { jp: "昔", en: "long ago" },
  { jp: "いくつかの", en: "some of" },
  { jp: "夜に", en: "at night" },
  { jp: "少しずつ", en: "little by little" },
  { jp: "機械の", en: "mechanical" },
  { jp: "重量", en: "weight" },
  { jp: "権力", en: "power" },
  { jp: "1時間", en: "hour" },
  { jp: "鈴", en: "bell" },
  { jp: "重い", en: "heavy" },
  { jp: "動かす", en: "move" },
  { jp: "改善する", en: "improve" },
  { jp: "光", en: "light" },
  { jp: "最終的に", en: "eventually" },
  { jp: "始めた", en: "began" },
  { jp: "始める", en: "begin" },
  { jp: "運ぶ", en: "carry" },
  { jp: "種類", en: "type" },
  { jp: "結果", en: "result" },
  { jp: "発明", en: "invention" },
  { jp: "努力", en: "effort" },
  { jp: "理解する", en: "recognize" },
  { jp: "考え", en: "idea" },
  { jp: "技術", en: "technology" },
  { jp: "知恵", en: "wisdom" },
  { jp: "する時だ", en: "it is time to" },
  { jp: "ホームステイ", en: "homestay" },
  { jp: "助言", en: "advice" },
  { jp: "会員", en: "member" },
  { jp: "客", en: "guest" },
  { jp: "従う", en: "follow" },
  { jp: "規則", en: "rule" },
  { jp: "主人", en: "host" },
  { jp: "完全な", en: "perfect" },
  { jp: "しなければならない", en: "have to" },
  { jp: "必要がある", en: "must" },
  { jp: "シャワー", en: "shower" },
  { jp: "制限", en: "limit" },
  { jp: "してはいけない", en: "mustn't" },
  { jp: "高齢の", en: "elderly" },
  { jp: "夫婦", en: "couple" },
  { jp: "居間", en: "living room" },
  { jp: "終える", en: "finish" },
  { jp: "何もない", en: "nothing" },
  { jp: "すべき", en: "should" },
  { jp: "皿", en: "plate" },
  { jp: "傷つける", en: "hurt" },
  { jp: "感情", en: "feeling" },
  { jp: "寝る", en: "go to bed" },
  { jp: "答える", en: "answer" },
  { jp: "入る", en: "enter" },
  { jp: "説明する", en: "explain" },
  { jp: "感じた", en: "felt" },
  { jp: "終わり", en: "end" },
  { jp: "続けた", en: "kept" },
  { jp: "続ける", en: "keep" },
  { jp: "注意深く", en: "carefully" },
  { jp: "脱ぐ", en: "take off" },
  { jp: "〜する気分", en: "feel like ing" },
  { jp: "最終的に", en: "in the end" },
  { jp: "お互いに", en: "each other" },
  { jp: "続けてやる", en: "keep ing" },
  { jp: "将来", en: "in the future" },
  { jp: "夫人", en: "Mrs." },
  { jp: "貴重な", en: "precious" },
  { jp: "できる", en: "be able to" },
  { jp: "幸運を祈る", en: "Best wishes," },
  { jp: "普遍的な", en: "universal" },
  { jp: "設計する", en: "design" },
  { jp: "公平な", en: "fair" },
  { jp: "自動の", en: "automatic" },
  { jp: "調整可能", en: "adjustable" },
  { jp: "公共の", en: "public" },
  { jp: "触れる", en: "touch" },
  { jp: "製品", en: "product" },
  { jp: "施設", en: "facility" },
  { jp: "市庁舎", en: "city hall" },
  { jp: "職員", en: "staff" },
  { jp: "軽くたたく", en: "tap" },
  { jp: "両方", en: "both" },
  { jp: "左利き", en: "left-handed" },
  { jp: "右利き", en: "right-handed" },
  { jp: "こちらへ", en: "over here" },
  { jp: "〜のおかげで", en: "thanks to" },
  { jp: "役に立つ", en: "useful" },
  { jp: "標識", en: "sign" },
  { jp: "若い", en: "young" },
  { jp: "傾斜路", en: "ramp" },
  { jp: "階段", en: "stair" },
  { jp: "車いす", en: "wheelchair" },
  { jp: "引く", en: "pull" },
  {jp: "荷物", en: "baggage" },
  { jp: "プレゼン", en: "presentation" },
  { jp: "アメリカ人", en: "American" },
  { jp: "教授", en: "professor" },
  { jp: "子供のころ", en: "childhood" },
  { jp: "取り除く", en: "remove" },
  { jp: "障害のある", en: "disabled" },
  { jp: "にも関わらず", en: "regardless" },
  { jp: "能力", en: "ability" },
  { jp: "状況", en: "situation" },
  { jp: "中心", en: "center" },
  { jp: "広げる", en: "spread" },
  { jp: "行きやすい", en: "accessible" },
  { jp: "にも関わらず", en: "regardless of" },
  { jp: "意味する", en: "mean" },
  { jp: "重い", en: "heavy" },
  { jp: "些細な事", en: "trivia" },
  { jp: "クイズ", en: "quiz" },
  { jp: "裁判所", en: "court" },
  { jp: "調査", en: "survey" },
  { jp: "カーリング", en: "curling" },
  { jp: "より多く", en: "more" },
  { jp: "戦略", en: "strategy" },
  { jp: "技術(技能)", en: "skill" },
  { jp: "最も", en: "most" },
  { jp: "図表", en: "graph" },
  { jp: "による", en: "according" },
  { jp: "パーセント", en: "percent" },
  { jp: "そのような", en: "such" },
  { jp: "結論", en: "conclusion" },
  { jp: "半分", en: "half" },
  { jp: "より良い", en: "better" },
  { jp: "によれば", en: "according to" },
  { jp: "について言えば", en: "as for" },
  { jp: "〜のような", en: "such as" },
  { jp: "結論として", en: "in conclusion" },
  { jp: "荷物", en: "baggage" },
  { jp: "プレゼン", en: "presentation" },
  { jp: "アメリカ人", en: "American" },
  { jp: "教授", en: "professor" },
  { jp: "子供のころ", en: "childhood" },
  { jp: "取り除く", en: "remove" },
  { jp: "障害のある", en: "disabled" },
  { jp: "にも関わらず", en: "regardless" },
  { jp: "能力", en: "ability" },
  { jp: "状況", en: "situation" },
  { jp: "中心", en: "center" },
  { jp: "広げる", en: "spread" },
  { jp: "行きやすい", en: "accessible" },
  { jp: "にも関わらず", en: "regardless of" },
  { jp: "意味する", en: "mean" },
  { jp: "重い", en: "heavy" },
  { jp: "些細な事", en: "trivia" },
  { jp: "クイズ", en: "quiz" },
  { jp: "裁判所", en: "court" },
  { jp: "調査", en: "survey" },
  { jp: "カーリング", en: "curling" },
  { jp: "より多く", en: "more" },
  { jp: "戦略", en: "strategy" },
  { jp: "技術(技能)", en: "skill" },
  { jp: "最も", en: "most" },
  { jp: "図表", en: "graph" },
  { jp: "による", en: "according" },
  { jp: "パーセント", en: "percent" },
  { jp: "そのような", en: "such" },
  { jp: "結論", en: "conclusion" },
  { jp: "半分", en: "half" },
  { jp: "より良い", en: "better" },
  { jp: "によれば", en: "according to" },
  { jp: "について言えば", en: "as for" },
  { jp: "〜のような", en: "such as" },
  { jp: "結論として", en: "in conclusion" },
]